# Generated by Django 4.1.4 on 2023-02-02 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(max_length=200, verbose_name='Тип кузова')),
            ],
            options={
                'verbose_name': 'Тип кузова',
                'verbose_name_plural': 'Типы кузова',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория автомобиля',
                'verbose_name_plural': 'Категории автомобилей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(blank=True, max_length=200, verbose_name='Название авто')),
                ('photo_start', models.ImageField(blank=True, upload_to='img/car/%Y/%m/%d/', verbose_name='Главное фото')),
                ('photo_1', models.ImageField(blank=True, upload_to='img/car/%Y/%m/%d/', verbose_name='Фото 2')),
                ('photo_2', models.ImageField(blank=True, upload_to='img/car/%Y/%m/%d/', verbose_name='Фото 3')),
                ('photo_3', models.ImageField(blank=True, upload_to='img/car/%Y/%m/%d/', verbose_name='Фото 4')),
                ('photo_4', models.ImageField(blank=True, upload_to='img/car/%Y/%m/%d/', verbose_name='Фото 5')),
            ],
            options={
                'verbose_name': 'Фотографии машин',
                'verbose_name_plural': 'Фотографии машин',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission', models.CharField(max_length=200, verbose_name='Тип топлива')),
            ],
            options={
                'verbose_name': 'Коробка передач',
                'verbose_name_plural': 'Коробки передач',
            },
        ),
        migrations.CreateModel(
            name='Type_fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_fuel', models.CharField(max_length=200, verbose_name='Тип топлива')),
            ],
            options={
                'verbose_name': 'Тип топлива',
                'verbose_name_plural': 'Типы топлива',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(blank=True, max_length=200, verbose_name='Модель')),
                ('register_num', models.CharField(blank=True, max_length=200, verbose_name='Регистрационный знак')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('places', models.IntegerField(blank=True, verbose_name='Количество мест')),
                ('price_one_five', models.FloatField(blank=True, verbose_name='Цена от 1 до 5 дней')),
                ('price_five_ten', models.FloatField(blank=True, verbose_name='Цена от 5 до 10 дней')),
                ('price_ten', models.FloatField(blank=True, verbose_name='Цена от 10 ')),
                ('video_review', models.URLField(blank=True, max_length=500, verbose_name='Обзор автомобиля')),
                ('engine_capacity', models.FloatField(blank=True, verbose_name='Объем двигателя')),
                ('power_engine', models.IntegerField(blank=True, verbose_name='Мощность двигателя')),
                ('body_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='car_app.body_type', verbose_name='Тип кузова')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_app.category', verbose_name='Категория')),
                ('color', models.ManyToManyField(blank=True, to='car_app.color', verbose_name='Цвет')),
                ('photo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='car_app.photo', verbose_name='Фото')),
                ('transmission', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='car_app.transmission', verbose_name='Коробки передач')),
                ('type_fuel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='car_app.type_fuel', verbose_name='Тип топлива')),
            ],
            options={
                'verbose_name': 'Автомобили',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['car_model'],
            },
        ),
    ]
